export const throwCustomError = (error: Error) => {
  throw error
}
